
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kamalia
 */
public class Question extends javax.swing.JFrame {
    int i;
    int id;
    String Answer;
    /**
     * Creates new form Question
     */
    public Question() {
        initComponents();
        Answer = "";
        i = 1;
        id = 0;
        setSize(690, 242);
        getQuestion();
        setVisible(true);        
        Submit.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e) {
                mark.setVisible(true);
                if(Jawaban.getText().equalsIgnoreCase(Answer)){
                    mark.setText("Benar");
                }
                else{
                    mark.setText("Salah, jawaban yang benar adalah " + Answer);
                }
                Next.setVisible(true);
            }
        });
        Next.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e) {
                getQuestion();
                Jawaban.setText("");
            }
        });
        Quit.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e) {
               dispose();
               setVisible(false);
               new MP();
            }
        });
    }
    
    public void getQuestion(){
        Next.setVisible(false);
        mark.setVisible(false);
        java.sql.Connection conn;
        try { 
            Class.forName("org.postgresql.Driver"); 
            String url = "jdbc:postgresql://localhost:5432/Peta_ITB"; 
            conn = DriverManager.getConnection(url, "postgres", "basdat");
            try (Statement s = conn.createStatement()) {
                ResultSet r = s.executeQuery("SELECT id, pertanyaan FROM question WHERE no_q = " + i);
                while(r.next()) {
                    id = r.getInt("id");
                    Soal.setText(r.getString("pertanyaan"));
                }
                r = s.executeQuery("SELECT nama FROM gedung WHERE id = " + id);
                while(r.next()) {
                    Answer = r.getString("nama");
                }
            }
            Soal.setVisible(true);
            conn.close(); 
            i++;
            if(i == 11){
                i = 1;
            }
        } 
        catch( ClassNotFoundException | SQLException e ) { 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Quit = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Soal = new javax.swing.JLabel();
        Jawaban = new javax.swing.JTextField();
        Next = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        mark = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tebak-Tebakan!!!");
        getContentPane().setLayout(null);

        Quit.setText("Quit");
        getContentPane().add(Quit);
        Quit.setBounds(320, 160, 83, 35);

        title.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        title.setText("Tebak-Tebakan!!!");
        getContentPane().add(title);
        title.setBounds(10, 11, 140, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Jawaban:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 90, 80, 30);

        Soal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Soal);
        Soal.setBounds(10, 50, 760, 20);

        Jawaban.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(Jawaban);
        Jawaban.setBounds(80, 90, 340, 30);

        Next.setText("Next");
        getContentPane().add(Next);
        Next.setBounds(600, 130, 70, 30);

        Submit.setText("Submit");
        getContentPane().add(Submit);
        Submit.setBounds(430, 90, 80, 30);

        mark.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mark.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(mark);
        mark.setBounds(80, 130, 430, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jawaban;
    private javax.swing.JButton Next;
    private javax.swing.JButton Quit;
    private javax.swing.JLabel Soal;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mark;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
